[2018-12-28 14:39:27 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6145)
[2018-12-28 14:54:06 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6144)
[2018-12-28 14:54:06 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6139)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6230)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6146)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6147)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6148)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6149)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6229)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6211)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6133)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6134)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6135)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6136)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6137)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6138)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6140)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6141)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6142)
[2018-12-28 14:57:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6143)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6239)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6240)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6241)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6242)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6243)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6244)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6245)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6246)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6247)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6248)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6249)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6251)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6252)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6253)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6254)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6255)
[2018-12-28 15:05:57 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6256)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6272)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6273)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6274)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6275)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6276)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6277)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6278)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6279)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6262)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6263)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6264)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6265)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6266)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6267)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6268)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6269)
[2018-12-28 15:18:26 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6270)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6336)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6337)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6321)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6322)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6323)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6324)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6325)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6326)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6327)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6328)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6329)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6330)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6331)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6332)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6333)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6334)
[2018-12-28 18:43:38 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6335)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6380)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6381)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6382)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6383)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6385)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6386)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6387)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6388)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6389)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6390)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6391)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6392)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6393)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6394)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6395)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6396)
[2018-12-28 22:04:39 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6397)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6400)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6401)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6402)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6403)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6404)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6405)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6406)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6407)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6408)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6410)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6413)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6414)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6415)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6416)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6418)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6419)
[2018-12-28 22:20:16 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6399)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6427)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6428)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6429)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6430)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6431)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6432)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6433)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6434)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6435)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6436)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6437)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6438)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6439)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6440)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6441)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6442)
[2018-12-29 10:06:18 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6443)
[2018-12-29 16:52:04 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6464)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6465)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6467)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6468)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6469)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6470)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6446)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6447)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6449)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6450)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6451)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6452)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6453)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6454)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6461)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6462)
[2018-12-29 16:52:05 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6463)
[2019-01-05 20:05:40 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6500)
[2019-01-05 20:05:40 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6501)
[2019-01-05 20:05:40 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6502)
[2019-01-05 20:05:40 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6503)
[2019-01-05 20:05:40 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6504)
[2019-01-05 20:05:40 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6505)
[2019-01-05 20:05:40 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6506)
[2019-01-05 20:05:40 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6507)
[2019-01-05 20:05:40 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6508)
[2019-01-05 20:05:40 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6509)
[2019-01-05 20:05:40 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6510)
[2019-01-05 20:05:40 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6511)
[2019-01-05 20:05:40 -0800] [6129] [CRITICAL] WORKER TIMEOUT (pid:6512)
[2019-01-06 01:02:32,870] ERROR in app: Exception on /jspsych-6.0.5/jspsych.js [GET]
Traceback (most recent call last):
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 726, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: jspsych-6.0.5/jspsych.js
[2019-01-06 01:20:31,387] ERROR in app: Exception on /images/T01.jpg [GET]
Traceback (most recent call last):
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 726, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: images/T01.jpg
[2019-01-06 01:21:18,347] ERROR in app: Exception on /images/T01.jpg [GET]
Traceback (most recent call last):
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 726, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: images/T01.jpg
[2019-01-06 01:31:37,560] ERROR in app: Exception on /images/T01.jpg [GET]
Traceback (most recent call last):
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 726, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: images/T01.jpg
[2019-01-06 01:31:59,734] ERROR in app: Exception on /images/T01.jpg [GET]
Traceback (most recent call last):
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 726, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: images/T01.jpg
[2019-01-06 01:33:06,806] ERROR in app: Exception on /images/T01.jpg [GET]
Traceback (most recent call last):
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 726, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: images/T01.jpg
[2019-01-06 01:33:29,639] ERROR in app: Exception on /images/T01.jpg [GET]
Traceback (most recent call last):
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 726, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: images/T01.jpg
[2019-01-06 01:33:30,401] ERROR in app: Exception on /images/T01.jpg [GET]
Traceback (most recent call last):
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 726, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: images/T01.jpg
[2019-01-06 01:34:17,637] ERROR in app: Exception on /images/T01.jpg [GET]
Traceback (most recent call last):
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 726, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: images/T01.jpg
[2019-01-06 01:36:01,757] ERROR in app: Exception on /images/T01.jpg [GET]
Traceback (most recent call last):
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 726, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: images/T01.jpg
[2019-01-06 01:36:49,932] ERROR in app: Exception on /images/T01.jpg [GET]
Traceback (most recent call last):
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 726, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: images/T01.jpg
[2019-01-06 01:36:50,733] ERROR in app: Exception on /images/T01.jpg [GET]
Traceback (most recent call last):
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 726, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: images/T01.jpg
[2019-01-06 03:04:08 -0800] [9572] [CRITICAL] WORKER TIMEOUT (pid:9592)
[2019-01-06 16:00:44 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9889)
[2019-01-06 16:00:44 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9890)
[2019-01-06 16:00:44 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9891)
[2019-01-06 16:00:44 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9892)
[2019-01-06 16:00:44 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9893)
[2019-01-06 16:00:44 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9894)
[2019-01-06 16:00:44 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9895)
[2019-01-06 16:00:44 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9896)
[2019-01-06 16:00:45 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9897)
[2019-01-06 16:00:45 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9899)
[2019-01-06 16:00:45 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9900)
[2019-01-06 16:00:45 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9901)
[2019-01-06 16:00:45 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9903)
[2019-01-06 16:00:45 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9904)
[2019-01-06 16:00:45 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9905)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:10112)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:10114)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:10115)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:10116)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:10117)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:10118)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:10119)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:10120)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:10121)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9898)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:10123)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:10124)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:10125)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:9902)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:10126)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:10122)
[2019-01-06 16:13:09 -0800] [9885] [CRITICAL] WORKER TIMEOUT (pid:10111)
[2019-01-06 20:55:02 -0800] [11822] [CRITICAL] WORKER TIMEOUT (pid:11827)
[2019-01-07 10:04:14 -0800] [838] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 47, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 89, in <module>
    init_db()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/db.py", line 37, in init_db
    Base.metadata.create_all(bind=engine)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2848, in create_all
    tables=tables)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1122, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 70, in visit_metadata
    self.traverse_single(table, create_ok=True)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 89, in visit_table
    self.connection.execute(schema.CreateTable(table))
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in _execute_ddl
    compiled
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) table agram_priming_dt already exists u'\nCREATE TABLE agram_priming_dt (\n\tuniqueid VARCHAR(128) NOT NULL, \n\tassignmentid VARCHAR(128) NOT NULL, \n\tworkerid VARCHAR(128) NOT NULL, \n\thitid VARCHAR(128) NOT NULL, \n\tipaddress VARCHAR(128), \n\tbrowser VARCHAR(128), \n\tplatform VARCHAR(128), \n\tlanguage VARCHAR(128), \n\tcond INTEGER, \n\tcounterbalance INTEGER, \n\tcodeversion VARCHAR(128), \n\tbeginhit DATETIME, \n\tbeginexp DATETIME, \n\tendhit DATETIME, \n\tbonus FLOAT, \n\tstatus INTEGER, \n\tmode VARCHAR(128), \n\tdatastring TEXT(4294967295), \n\tPRIMARY KEY (uniqueid)\n)\n\n' ()
Traceback (most recent call last):
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment_server.py", line 47, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 89, in <module>
    init_db()
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/db.py", line 37, in init_db
    Base.metadata.create_all(bind=engine)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/schema.py", line 2848, in create_all
    tables=tables)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1479, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1122, in _run_visitor
    **kwargs).traverse_single(element)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 70, in visit_metadata
    self.traverse_single(table, create_ok=True)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 122, in traverse_single
    return meth(obj, **kw)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/ddl.py", line 89, in visit_table
    self.connection.execute(schema.CreateTable(table))
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 720, in _execute_ddl
    compiled
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/Users/cheryang/.edm/envs/psiturk/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (OperationalError) table agram_priming_dt already exists u'\nCREATE TABLE agram_priming_dt (\n\tuniqueid VARCHAR(128) NOT NULL, \n\tassignmentid VARCHAR(128) NOT NULL, \n\tworkerid VARCHAR(128) NOT NULL, \n\thitid VARCHAR(128) NOT NULL, \n\tipaddress VARCHAR(128), \n\tbrowser VARCHAR(128), \n\tplatform VARCHAR(128), \n\tlanguage VARCHAR(128), \n\tcond INTEGER, \n\tcounterbalance INTEGER, \n\tcodeversion VARCHAR(128), \n\tbeginhit DATETIME, \n\tbeginexp DATETIME, \n\tendhit DATETIME, \n\tbonus FLOAT, \n\tstatus INTEGER, \n\tmode VARCHAR(128), \n\tdatastring TEXT(4294967295), \n\tPRIMARY KEY (uniqueid)\n)\n\n' ()
[2019-01-10 10:30:30 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6004)
[2019-01-10 10:30:30 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6005)
[2019-01-10 10:30:30 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6006)
[2019-01-10 10:30:30 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6008)
[2019-01-10 10:30:30 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6009)
[2019-01-10 10:30:30 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6010)
[2019-01-10 10:30:30 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6011)
[2019-01-10 10:30:30 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6012)
[2019-01-10 10:30:30 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6013)
[2019-01-10 10:36:09 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6784)
[2019-01-10 10:52:09 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6785)
[2019-01-10 10:52:09 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6786)
[2019-01-10 10:52:09 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6787)
[2019-01-10 10:52:09 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6788)
[2019-01-10 10:52:09 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6789)
[2019-01-10 10:52:09 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6803)
[2019-01-10 10:52:09 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6781)
[2019-01-10 10:52:09 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6782)
[2019-01-10 10:52:09 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:6783)
[2019-01-10 11:31:04 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7008)
[2019-01-10 11:31:04 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7009)
[2019-01-10 11:31:04 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7013)
[2019-01-10 11:31:04 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7014)
[2019-01-10 11:31:04 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7015)
[2019-01-10 11:31:04 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7007)
[2019-01-10 12:08:17 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7010)
[2019-01-10 12:08:17 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7011)
[2019-01-10 12:08:17 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7012)
[2019-01-10 12:08:17 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7622)
[2019-01-10 12:08:17 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7623)
[2019-01-10 12:08:17 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7618)
[2019-01-10 12:08:17 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7619)
[2019-01-10 12:08:17 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7620)
[2019-01-10 12:08:17 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7621)
[2019-01-10 13:22:57 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7744)
[2019-01-10 13:22:57 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7745)
[2019-01-10 13:22:57 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7746)
[2019-01-10 13:22:57 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7747)
[2019-01-10 13:22:57 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7748)
[2019-01-10 13:22:57 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7743)
[2019-01-10 13:22:57 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7740)
[2019-01-10 13:22:57 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7741)
[2019-01-10 13:22:57 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7742)
[2019-01-10 13:31:55 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7776)
[2019-01-10 13:31:55 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7767)
[2019-01-10 13:31:55 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7768)
[2019-01-10 13:31:55 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7769)
[2019-01-10 13:31:55 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7771)
[2019-01-10 13:31:55 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7772)
[2019-01-10 13:31:55 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7773)
[2019-01-10 13:31:55 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7774)
[2019-01-10 13:31:55 -0800] [6000] [CRITICAL] WORKER TIMEOUT (pid:7775)
[2019-01-16 21:25:11 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:670)
[2019-01-16 21:38:27 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:662)
[2019-01-16 21:38:27 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:667)
[2019-01-17 00:43:24 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:669)
[2019-01-17 01:10:19 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:933)
[2019-01-17 01:10:19 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:934)
[2019-01-17 01:10:19 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:747)
[2019-01-17 01:10:19 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:661)
[2019-01-17 01:10:19 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:663)
[2019-01-17 01:10:19 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:665)
[2019-01-17 01:10:19 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:666)
[2019-01-17 01:10:19 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:668)
[2019-01-17 01:10:19 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1493)
[2019-01-17 01:28:10 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1509)
[2019-01-17 01:28:10 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1510)
[2019-01-17 01:28:10 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1511)
[2019-01-17 01:28:10 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1513)
[2019-01-17 01:28:10 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1514)
[2019-01-17 01:28:10 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1515)
[2019-01-17 01:28:10 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1516)
[2019-01-17 01:28:10 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1517)
[2019-01-17 01:28:10 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1518)
[2019-01-17 01:34:20 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1524)
[2019-01-17 01:34:20 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1525)
[2019-01-17 01:34:20 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1526)
[2019-01-17 01:34:20 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1527)
[2019-01-17 01:34:20 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1528)
[2019-01-17 01:34:20 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1529)
[2019-01-17 01:34:20 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1530)
[2019-01-17 01:34:20 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1531)
[2019-01-17 01:34:20 -0800] [657] [CRITICAL] WORKER TIMEOUT (pid:1532)
[2019-01-17 14:24:00 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2017)
[2019-01-17 14:24:00 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2018)
[2019-01-17 14:24:00 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2019)
[2019-01-17 14:24:00 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2020)
[2019-01-17 14:24:00 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2021)
[2019-01-17 14:24:00 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2022)
[2019-01-17 14:24:00 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2023)
[2019-01-17 14:24:00 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2024)
[2019-01-17 14:24:00 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2025)
[2019-01-17 15:40:26 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2343)
[2019-01-17 15:40:26 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2346)
[2019-01-17 15:40:26 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2347)
[2019-01-17 15:40:26 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2348)
[2019-01-17 15:40:26 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2349)
[2019-01-17 15:40:26 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2350)
[2019-01-17 15:40:26 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2351)
[2019-01-17 15:40:26 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2352)
[2019-01-17 15:40:26 -0800] [2013] [CRITICAL] WORKER TIMEOUT (pid:2344)
[2019-01-17 16:04:07,507] ERROR in app: Exception on /undefined [GET]
Traceback (most recent call last):
  File "/Users/Cher/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Cher/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Cher/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Cher/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Cher/.edm/envs/psiturk/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Cher/.edm/envs/psiturk/lib/python2.7/site-packages/psiturk/experiment.py", line 724, in regularpage
    return render_template(pagename)
  File "/Users/Cher/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/Cher/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/Cher/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/Cher/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/Cher/.edm/envs/psiturk/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/Cher/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/Cher/.edm/envs/psiturk/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: undefined
